# Generated by Django 3.0 on 2021-04-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med', '0002_auto_20210430_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Medicininst'), (2, 'Organisation'), (3, 'Anonymous')], default=3),
        ),
    ]
